# Generated by Django 5.1.2 on 2024-10-23 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_abv_alter_product_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bottler',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bottler',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bottler',
            name='link_text',
            field=models.CharField(blank=True, default='Visit Website', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='productbrand',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productbrand',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='producttastingnote',
            name='finish',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='producttastingnote',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='producttastingnote',
            name='nose',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='producttastingnote',
            name='origin',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='producttastingnote',
            name='overall',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='producttastingnote',
            name='palate',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='producttype',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
