# Generated by Django 5.1.2 on 2024-10-24 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_list_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(default='EUR', max_length=100)),
                ('long_name', models.CharField(default='Euro', max_length=100)),
                ('symbol', models.CharField(default='€', max_length=5)),
                ('conervsion_rate', models.DecimalField(decimal_places=4, default=1.0, max_digits=6)),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='product_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_category', to='products.productcategory'),
        ),
        migrations.AddField(
            model_name='product',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='currency', to='products.currency'),
        ),
    ]
