# Generated by Django 5.1.2 on 2024-11-05 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_product_featured'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='featured',
        ),
    ]
