# Generated by Django 5.1.2 on 2024-11-08 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_remove_product_featured'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producttastingnote',
            name='product',
        ),
        migrations.AlterUniqueTogether(
            name='producttastecategory',
            unique_together={('product', 'taste_category')},
        ),
        migrations.DeleteModel(
            name='ProductReview',
        ),
        migrations.DeleteModel(
            name='ProductTastingNote',
        ),
    ]
