# Generated by Django 5.1.2 on 2024-11-10 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_remove_producttastingnote_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bottler',
            name='alt_text',
            field=models.CharField(blank=True, default='logo', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bottler',
            name='name',
            field=models.CharField(default='Original Brand', max_length=100),
        ),
        migrations.AlterField(
            model_name='casktype',
            name='name',
            field=models.CharField(default='Wooden Cask', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.ForeignKey(blank=True, default='Whiskey', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_type', to='products.producttype'),
        ),
        migrations.AlterField(
            model_name='productbrand',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='productsize',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='producttype',
            name='name',
            field=models.CharField(default='Whiskey', max_length=100),
        ),
        migrations.AlterField(
            model_name='tastecategory',
            name='alt_text',
            field=models.CharField(blank=True, default='icon', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tastecategory',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tastecategory',
            name='fa_icon',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tastecategory',
            name='name',
            field=models.CharField(max_length=250),
        ),
    ]
